---
development:
  cloud_name: db9ynxluy
  api_key: '763938797749984'
  api_secret: ZQLCY35cWACo81bolMh08zR3nN8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: db9ynxluy
  api_key: '763938797749984'
  api_secret: ZQLCY35cWACo81bolMh08zR3nN8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: db9ynxluy
  api_key: '763938797749984'
  api_secret: ZQLCY35cWACo81bolMh08zR3nN8
  enhance_image_tag: true
  static_image_support: false