development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: free_lunch
  pool: 5
  username: ubuntu
  password: racine93!

test: &TEST
  adapter: postgresql
  encoding: SQL_ASCII
  database: free_lunch_test
  pool: 5
  username: ubuntu
  password: racine93!

production:
  adapter: postgresql
  encoding: SQL_ASCII
  database: free_lunch_production
  pool: 5
  username: ubuntu
  password: racine93!